### ISSUE TITLE
Echo flag gets printed on macOS

### ISSUE THREAD

**Issue by rcopstein** [Taeluf/Git-Bent#2]
When using the flag ```-e``` for the ```echo``` command on macOS, the flag is not interpreted and gets printed instead.

Linux:
```bash
echo -e "Linux\nOutput"
```
outputs
```
Linux
Output
```

macOS:
```bash
echo -e "macOS\nOutput"
```
outputs
```
-e macOS
Output
```

**Comment by Taeluf** [comment]
Thank you, that's awesome! I'm guessing there will be more things like this to come. Hopefully not too much for windows compatibility, especially since they have the linux subsystem now (but I don't really know much about that)

Your PR looks good. I'm re-doing the folder structure & writing some TODOs & contribution notes right now. I'll merge your PR in a little bit.

**Comment by Taeluf** [comment]
I did update using an `msg` function & replaced all the `echo -e`, but left regular `echo`. When I tried replacing every `echo`... some things broke, so I thought it safer not to do it everywhere for now.

I kept your version of calling the os setup at the beginning of `bent.sh`, &  modified it to be:
```bash
if [ "$(uname)" == "Darwin" ]; then
    OS="MAC"
    # If necessary, call for macOS 
    # specific initialization code

elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
    OS="LINUX"
else
    OS="OTHER"
fi

msg(){
    if [[ $OS == "MAC" ]]; then
        echo "$1" "$2" "$3"
    else 
        echo -e "$1" "$2" "$3"
    fi
}
```

This way `uname` is being called just once. I figured the `msg` function belonged in the `os.sh` file, since it is aware & I'm not sure how to get around that.

**Comment by Taeluf** [comment]
& in case you wondered, I wrote it like `echo "$1" "$2" "$3"` because I'm using `echo -n` in a couple places, so the message was arg2 & I figured... maybe there'll be a third argument sometime...

Hopefully the extra args don't cause an error on mac! Let me know if the colors stopped working or anything broke.

I also changed up the directory structure (had been putting that off).

**Comment by Taeluf** [comment]
Oh, and thank you for your help! :) 
On linux, at least on Fedora 32, the `-e` is what made the colors work. `printf` was an alternate solution, but that doesn't print newlines automatically & I honestly haven't used it. Using `echo "\e COLOR message"` might be a valid option, too.

**Comment by Taeluf** [comment]
I'm assuming the original issue "Echo flag gets printed on macOS" is resolved now, thus closing. :)
